const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.NODE_OVERVIEW_URL);
 await page.locator('.node-focus-title').waitFor();
 assert.equal(await page.locator('.node-focus-title').innerText(),'第一评审');
 assert.equal(await page.locator('.node-current-label').count(),1);
 assert.ok((await page.locator('#overview-phase-summary').innerText()).includes('交付物规则待设置'));
 await page.locator('#overview-phase-summary .timeline-edit-btn').click();
 const first=page.locator('.milestone-edit-row').first();
 await first.locator('input[name="name"]').fill('第一评审（完成）');
 await first.locator('select[name="type"]').selectOption('done');
 const save=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().endsWith('/milestones'));
 await page.locator('.milestone-save-btn').click();
 assert.equal((await save).status(),200);
 await page.locator('#overview-tab-status').click();
 assert.equal(await page.locator('.node-focus-title').innerText(),'第二评审');
 await page.reload();
 await page.locator('.node-focus-title').waitFor();
 assert.equal(await page.locator('.node-focus-title').innerText(),'第二评审');
 await page.locator('#overview-phase-summary .timeline-edit-btn').click();
 assert.equal(await page.locator('.milestone-edit-row').first().locator('input[name="name"]').inputValue(),'第一评审（完成）');
 await page.locator('.milestone-edit-row').nth(1).locator('input[name="name"]').fill('放弃的改名');
 page.once('dialog',d=>d.accept());
 await page.locator('.milestone-cancel-btn').click();
 await page.locator('#overview-tab-status').click();
 assert.equal(await page.locator('.node-focus-title').innerText(),'第二评审');
 await page.screenshot({path:'.runtime/node-overview-production.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: real UI save, rename, completion advances node, reload persistence, cancel, mobile width, no page errors');
})().catch(e=>{console.error(e);process.exit(1)});
