# -*- coding: utf-8 -*-
"""Scaffold a feature plugin under ``plugins/<id>/``.

Usage::

    python tools/new_plugin.py my-report --name "我的报表"
    python tools/new_plugin.py my-report --name "我的报表" --page summary --title "汇总" --kind module

Generates ``plugin.json``, ``backend.py`` (one ``GET rows`` route), a page
(``static/pages/<page>.json`` schema or ``static/<page>.js`` module) and a
contract test in ``tests/``. Then run ``python webui.py --only <id>`` and
open ``#p/<id>/<page>``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from host.plugin import HOST_API_VERSION, PluginManifestError, parse_manifest  # noqa: E402

_BACKEND = '''# -*- coding: utf-8 -*-
"""{name} plugin backend. Routes are mounted at /api/p/{plugin_id}/."""

from __future__ import annotations


def register(host):
    ctx = host.context

    @host.blueprint.get("/rows")
    def rows():
        # TODO: 读取数据。共享服务只能经 ctx 获取（ctx.db、ctx.service(...)），不要 import web.*。
        data = [
            {{"id": 1, "name": "示例 A", "group": "一组", "done": True}},
            {{"id": 2, "name": "示例 B", "group": "二组", "done": False}},
        ]
        return ctx.json_ok({{"rows": data}})
'''

_MODULE_PAGE = '''// {title}: plugin module page. Shared runtime and UI Kit come from the host.
import {{ html }} from "/static/host/vendor/preact-htm.js";
import {{ DataTable, StateBlock }} from "/static/host/kit.js";
import {{ useResource }} from "/static/host/api.js";

const COLUMNS = [
  {{ key: "name", title: "名称" }},
  {{ key: "group", title: "分组" }},
];

export default function Page({{ api }}) {{
  const res = useResource(api.url("rows"));
  if (!res.data) return html`<${{StateBlock}} loading=${{res.loading}} error=${{res.error}} onRetry=${{res.reload}} />`;
  return html`<div class="vk-page">
    <header class="vk-page-header"><h2>{title}</h2></header>
    <${{DataTable}} columns=${{COLUMNS}} rows=${{res.data.rows}} />
  </div>`;
}}
'''

_TEST = '''# -*- coding: utf-8 -*-
"""Contract test for the {plugin_id} plugin (generated by tools/new_plugin.py)."""

from __future__ import annotations

from pathlib import Path

import web.app as web_app

PLUGINS_ROOT = Path(__file__).resolve().parent.parent / "plugins"


def test_{module}_plugin_loads_and_serves_rows(monkeypatch, tmp_path):  # type: ignore[no-untyped-def]
    db_cls = web_app.DatabaseManager
    monkeypatch.setattr(web_app, "DatabaseManager", lambda: db_cls(tmp_path / "plugin.db"))
    app = web_app.create_app(plugin_dirs=[PLUGINS_ROOT], plugin_only=["{plugin_id}"])
    client = app.test_client()

    manifest = client.get("/api/host/manifest").get_json()["data"]
    record = next(p for p in manifest["plugins"] if p["id"] == "{plugin_id}")
    assert record["status"] == "loaded", record.get("error")

    body = client.get("/api/p/{plugin_id}/rows").get_json()
    assert body["ok"] is True
    assert isinstance(body["data"]["rows"], list)
'''


def _schema_page(title: str) -> dict:
    return {
        "renderer": "analysis",
        "title": title,
        "source": "rows",
        "filters": [
            {"key": "name", "label": "名称", "type": "text"},
            {"key": "group", "label": "分组", "optionsFromRows": True},
        ],
        "charts": [{"type": "doneBars", "id": "group", "title": "按分组", "groupBy": "group", "doneField": "done"}],
        "columns": [{"key": "name", "title": "名称"}, {"key": "group", "title": "分组"}],
        "rowKey": "id",
    }


def scaffold(
    plugin_id: str,
    name: str,
    *,
    page: str = "main",
    title: str | None = None,
    kind: str = "schema",
    plugins_root: Path | None = None,
    tests_root: Path | None = None,
) -> list[Path]:
    """Create the plugin files; returns the paths written. Refuses to overwrite."""
    title = title or name
    host_major = int(HOST_API_VERSION.split(".")[0])
    page_entry: dict = {"id": page, "title": title, "kind": kind}
    if kind == "module":
        page_entry["module"] = f"{page}.js"
    manifest = {
        "id": plugin_id,
        "name": name,
        "version": "0.1.0",
        "hostApi": f">={host_major},<{host_major + 1}",
        "description": "",
        "pages": [page_entry],
        "nav": [{"title": title, "page": page, "order": 100}],
    }
    parse_manifest(manifest)  # same validation the host applies at startup

    plugins_root = plugins_root or REPO_ROOT / "plugins"
    tests_root = tests_root or REPO_ROOT / "tests"
    module = plugin_id.replace("-", "_")
    plugin_dir = plugins_root / module
    test_path = tests_root / f"test_plugin_{module}.py"
    if plugin_dir.exists():
        raise FileExistsError(f"{plugin_dir} 已存在")
    if test_path.exists():
        raise FileExistsError(f"{test_path} 已存在")

    files: dict[Path, str] = {
        plugin_dir / "plugin.json": json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        plugin_dir / "backend.py": _BACKEND.format(name=name, plugin_id=plugin_id),
        test_path: _TEST.format(plugin_id=plugin_id, module=module),
    }
    if kind == "module":
        files[plugin_dir / "static" / f"{page}.js"] = _MODULE_PAGE.format(title=title)
    else:
        files[plugin_dir / "static" / "pages" / f"{page}.json"] = (
            json.dumps(_schema_page(title), ensure_ascii=False, indent=2) + "\n"
        )
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return list(files)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="生成标准插件目录 plugins/<id>/")
    parser.add_argument("plugin_id", help="插件 id：小写字母开头，可含数字、- 和 _")
    parser.add_argument("--name", required=True, help="插件显示名称")
    parser.add_argument("--page", default="main", help="首个页面 id（默认 main）")
    parser.add_argument("--title", help="页面与导航标题（默认同 --name）")
    parser.add_argument("--kind", choices=("schema", "module"), default="schema", help="页面类型（默认 schema）")
    args = parser.parse_args(argv)
    try:
        written = scaffold(args.plugin_id, args.name, page=args.page, title=args.title, kind=args.kind)
    except (PluginManifestError, FileExistsError) as exc:
        print(f"错误：{exc}", file=sys.stderr)
        return 2
    for path in written:
        print(f"created {path.relative_to(REPO_ROOT)}")
    print(f"\n下一步：python webui.py --only {args.plugin_id}，然后打开 #p/{args.plugin_id}/{args.page}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
